/** Authored, dependency-free effects. The same documents run in the gallery, sample and ZIP. */
export const ELEMENTS = [
  { id: "aurora", title: "Aurora mesh", category: "Backgrounds", description: "Slow-moving fields of colour. A little atmosphere, a lot of possibility.", tag: "AMBIENT", html: '<div class="aurora"></div><div class="center"><small>MAKE ROOM FOR POSSIBILITY</small><h1>Something<br>extraordinary.</h1></div>', css: '.aurora{position:absolute;inset:-60%;background:radial-gradient(ellipse at 35% 50%,#a3e63588,transparent 35%),radial-gradient(ellipse at 65% 45%,#8b5cf699,transparent 30%),radial-gradient(ellipse at 50% 70%,#22d3ee66,transparent 30%);filter:blur(35px);animation:drift 12s ease-in-out infinite alternate}@keyframes drift{to{transform:rotate(35deg) scale(1.2)}}', js: "" },
  { id: "split-text", title: "Split text reveal", category: "Text animations", description: "A staggered entrance that gives every letter a moment.", tag: "TEXT", html: '<div class="center"><small>WORDS WITH A LITTLE MORE</small><h1 class="split">Character.</h1><span class="hint">Click to replay ↻</span></div>', css: '.split{display:flex;overflow:hidden}.split span{display:inline-block;animation:rise 3.5s both infinite;animation-delay:calc(var(--i)*70ms)}@keyframes rise{0%,10%{transform:translateY(110%) rotate(8deg);opacity:0}35%,90%{transform:none;opacity:1}100%{opacity:0}}', js: 'const text=document.querySelector(".split");text.innerHTML=[...text.textContent].map((c,i)=>`<span style="--i:${i}">${c}</span>`).join("");document.body.onclick=()=>{text.getAnimations({subtree:true}).forEach(a=>a.currentTime=0)};' },
  { id: "orbit", title: "Orbital system", category: "Backgrounds", description: "An animated constellation for your next big idea.", tag: "LOOP", html: '<div class="orbit"><div class="ring r1"><i></i></div><div class="ring r2"><i></i></div><div class="ring r3"><i></i></div><b>✳</b></div>', css: '.orbit{width:230px;height:230px;position:relative;display:grid;place-items:center}.orbit b{font-size:65px;color:var(--accent)}.ring{position:absolute;border:1px solid #ffffff22;border-radius:50%;inset:15px;animation:spin 12s linear infinite}.ring i{position:absolute;left:50%;top:-5px;width:10px;height:10px;border-radius:50%;background:var(--accent);box-shadow:0 0 20px var(--accent)}.r2{inset:45px;animation-duration:8s;animation-direction:reverse;transform:rotate(80deg)}.r3{inset:0;animation-duration:19s}.r3 i{background:#b5a0f5}@keyframes spin{to{transform:rotate(360deg)}}', js: "" },
  { id: "magnetic", title: "Magnetic attraction", category: "Hover effects", description: "A call to action that gently follows your pointer.", tag: "INTERACTIVE", html: '<div class="center"><small>A LITTLE CLOSER</small><button class="magnet">Let’s make it happen <span>↗</span></button><span class="hint">Move your cursor around the button</span></div>', css: '.magnet{padding:20px 26px;border-radius:50px;background:var(--accent);color:#15180e;border:0;font-size:16px;transition:transform .18s ease-out}.magnet span{margin-left:25px}', js: 'const b=document.querySelector("button");document.onpointermove=e=>{const r=b.getBoundingClientRect();b.style.transform=`translate(${(e.clientX-r.left-r.width/2)*.15}px,${(e.clientY-r.top-r.height/2)*.15}px)`};document.onpointerleave=()=>b.style.transform="";' },
  { id: "marquee", title: "Infinite marquee", category: "Scroll effects", description: "A seamless ribbon of words, logos, or whatever comes next.", tag: "LOOP", html: '<div class="marquee"><div>CREATE ✳ EXPLORE ✳ REPEAT ✳ CREATE ✳ EXPLORE ✳ REPEAT ✳ </div></div>', css: '.marquee{width:100%;overflow:hidden;transform:rotate(-7deg);border-block:1px solid #ffffff22;padding:25px 0;background:var(--accent);color:#171911}.marquee div{white-space:nowrap;font-size:42px;font-weight:800;width:max-content;animation:marquee 18s linear infinite}.marquee:hover div{animation-play-state:paused}@keyframes marquee{to{transform:translateX(-50%)}}', js: "" },
  { id: "spotlight", title: "Spotlight card", category: "Hover effects", description: "A soft pool of light follows you across the surface.", tag: "INTERACTIVE", html: '<article class="spot"><span>✳</span><h2>A brighter idea.</h2><p>There’s something here.<br>Take a closer look.</p><b>Explore the possibilities ↗</b></article>', css: '.spot{width:240px;border:1px solid #ffffff22;border-radius:16px;padding:26px;background:radial-gradient(200px circle at var(--x,50%) var(--y,0%),#d1ee9935,transparent),#181a19}.spot>span{font-size:38px;color:var(--accent)}.spot h2{font-size:24px;margin:18px 0 10px}.spot p{line-height:1.6;color:#a1a5a0;font-size:13px}.spot b{font-size:11px;font-weight:400}', js: 'const c=document.querySelector(".spot");c.onpointermove=e=>{const r=c.getBoundingClientRect();c.style.setProperty("--x",`${e.clientX-r.left}px`);c.style.setProperty("--y",`${e.clientY-r.top}px`)};' },
  { id: "stack", title: "Scroll card stack", category: "Scroll effects", description: "Sticky cards that stack as you move through a story.", tag: "SCROLL", html: '<div class="scroll-area"><small>SCROLL TO DISCOVER ↓</small><article class="stack one"><span>01 / DISCOVER</span><h2>Find your<br>perspective.</h2></article><article class="stack two"><span>02 / EXPLORE</span><h2>Make it<br>your own.</h2></article><article class="stack three"><span>03 / CREATE</span><h2>Bring it<br>to life.</h2></article><div style="height:180px"></div></div>', css: 'body{display:block!important}.scroll-area{height:100vh;overflow:auto;padding:25px;box-sizing:border-box}.scroll-area>small{display:block;text-align:center;padding-bottom:20px}.stack{position:sticky;top:10px;border-radius:14px;padding:24px;height:190px;box-sizing:border-box;margin-bottom:30px;color:#181b16}.stack span{font-size:10px}.stack h2{font-size:35px;margin:15px 0}.one{background:var(--accent)}.two{background:#b8a4e9;top:25px}.three{background:#f0b88a;top:40px}', js: "" },
  { id: "cursor-trail", title: "Cursor constellation", category: "Cursor effects", description: "Leave a fleeting constellation wherever you go.", tag: "POINTER", html: '<div class="center"><div style="font-size:54px;color:var(--accent)">↖</div><h2>Follow your curiosity.</h2><span class="hint">Move your cursor across this canvas</span></div>', css: '.spark{position:fixed;pointer-events:none;width:7px;height:7px;background:var(--accent);border-radius:50%;animation:vanish .7s forwards}@keyframes vanish{to{transform:translateY(30px) scale(0);opacity:0}}', js: 'let last=0;document.onpointermove=e=>{if(performance.now()-last<30)return;last=performance.now();const s=document.createElement("i");s.className="spark";s.style.left=e.clientX+"px";s.style.top=e.clientY+"px";document.body.append(s);setTimeout(()=>s.remove(),700)};' },
  { id: "reveal", title: "Scroll reveal", category: "Scroll effects", description: "Content comes into focus as it enters the viewport.", tag: "SCROLL", html: '<div class="reveal-scroll"><small>SCROLL INSIDE TO REVEAL ↓</small><h1>Every detail.<br>A discovery.</h1><div class="reveal-block">A new perspective.</div><div class="reveal-block">Room to explore.</div><div class="reveal-block">Made for you.</div></div>', css: 'body{display:block!important}.reveal-scroll{height:100vh;overflow:auto;padding:30px;box-sizing:border-box}.reveal-scroll h1{font-size:40px;margin:45px 0}.reveal-block{padding:50px 20px;border:1px solid #ffffff22;border-radius:12px;margin:25px 0;font-size:27px;opacity:.2;transform:translateY(20px);transition:all .7s}.reveal-block.visible{opacity:1;transform:none;color:var(--accent)}', js: 'const o=new IntersectionObserver(es=>es.forEach(e=>e.target.classList.toggle("visible",e.isIntersecting)),{root:document.querySelector(".reveal-scroll"),threshold:.5});document.querySelectorAll(".reveal-block").forEach(n=>o.observe(n));' },
  { id: "tilt", title: "Perspective tilt", category: "Hover effects", description: "A dimensional surface that responds to your movement.", tag: "3D", html: '<article class="tilt"><small>THE NEXT DIMENSION</small><div>✳</div><strong>A different angle.</strong><span>Move to explore ↗</span></article>', css: '.tilt{width:250px;height:200px;border:1px solid #c7eba766;border-radius:18px;padding:25px;background:linear-gradient(135deg,#263225,#131714);transition:transform .15s;transform-style:preserve-3d}.tilt div{font-size:75px;color:var(--accent);margin:15px 0}.tilt strong{display:block;font-size:23px}.tilt span{display:block;font-size:11px;color:#929d90;margin-top:15px}', js: 'const c=document.querySelector(".tilt");c.onpointermove=e=>{const r=c.getBoundingClientRect();c.style.transform=`perspective(700px) rotateX(${-(e.clientY-r.top-r.height/2)/12}deg) rotateY(${(e.clientX-r.left-r.width/2)/12}deg)`};c.onpointerleave=()=>c.style.transform="";' },
  { id: "gradient-text", title: "Chromatic type", category: "Text animations", description: "An animated gradient that flows through your headline.", tag: "TEXT", html: '<div class="center"><small>LET YOUR IDEAS</small><h1 class="gradient">Take shape.</h1><span class="hint">Colour in constant motion</span></div>', css: '.gradient{background:linear-gradient(100deg,var(--accent),#ac93e8,#76d4d8,var(--accent));background-size:300%;background-clip:text;color:transparent;animation:flow 6s linear infinite}@keyframes flow{to{background-position:300%}}', js: "" },
  { id: "gallery", title: "Expanding gallery", category: "Galleries", description: "A collection that opens up as you hover or focus.", tag: "INTERACTIVE", html: '<div class="gallery"><button aria-label="Explore green landscape"><span>01<br>Discover</span></button><button aria-label="Explore violet landscape"><span>02<br>Imagine</span></button><button aria-label="Explore warm landscape"><span>03<br>Create</span></button></div>', css: '.gallery{display:flex;width:90%;height:220px;gap:8px}.gallery button{flex:1;min-width:0;border:0;border-radius:12px;transition:flex .5s;position:relative;overflow:hidden;background:radial-gradient(ellipse at 50% 120%,#0a1110 40%,transparent 41%),linear-gradient(160deg,#d7edb2,#526e60);color:white}.gallery button:nth-child(2){background:radial-gradient(ellipse at 70% 0%,#e0c9fa,transparent 65%),#685387}.gallery button:nth-child(3){background:radial-gradient(circle at 90% 30%,#f4d4a5,transparent 55%),#b47055}.gallery button:hover,.gallery button:focus{flex:3}.gallery span{position:absolute;bottom:20px;left:16px;text-align:left;line-height:1.8;font-size:12px}', js: "" },
] as const;
export type ElementId = (typeof ELEMENTS)[number]["id"];
export function elementOrigin(id: string) {
  const item = ELEMENTS.find(e => e.id === id);
  return { name: "Playground Originals", runtime: item?.js ? "CSS + JavaScript" : "CSS" };
}
export function elementDocument(id: string, accent = "#d2ef9e"): string {
  const item = ELEMENTS.find((e) => e.id === id);
  if (!item) return "";
  const safeAccent = /^#[a-f0-9]{6}$/i.test(accent) ? accent : "#d2ef9e";
  return `<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${item.title}</title><style>
  :root{--accent:${safeAccent};color-scheme:dark}*{box-sizing:border-box}body{margin:0;height:100vh;overflow:hidden;display:flex;align-items:center;justify-content:center;background:#111412;color:#f2f3ed;font-family:Arial,sans-serif;position:relative}button{font:inherit;cursor:pointer}button:focus-visible{outline:2px solid var(--accent);outline-offset:4px}.center{position:relative;text-align:center;display:flex;align-items:center;flex-direction:column;gap:20px}h1{font-size:clamp(28px,8vw,55px);letter-spacing:-.065em;line-height:1.05;margin:0;font-weight:600}h2{letter-spacing:-.04em}small{font-size:9px;letter-spacing:2px;color:#a4af9b}.hint{font-size:10px;color:#8b968b}${item.css}
  @media(prefers-reduced-motion:reduce){*,*::before,*::after{animation:none!important;transition:none!important;scroll-behavior:auto!important}.split span,.reveal-block{opacity:1!important;transform:none!important}}
  </style><body>${item.html}<script>if(!matchMedia('(prefers-reduced-motion: reduce)').matches){${item.js}}</script></body></html>`;
}
