import { CHART_ELEMENTS } from "./chart-elements";
import { ENGINE_ELEMENTS } from "./engine-elements";
/** Playground-authored demos. Engine attribution describes the runtime, not authorship. */
export const ENGINE_SOURCES = [
  { id: "motion", label: "Motion.dev", url: "https://motion.dev/docs" },
  { id: "lenis", label: "Lenis", url: "https://github.com/darkroomengineering/lenis" },
  { id: "vanta", label: "Vanta", url: "https://www.vantajs.com/" },
] as const;
export function engineFor(id: string) { return ENGINE_SOURCES.find(s => id.startsWith(`${s.id}-`)); }

const palettes = ["#e5bcb0", "#c6d9a4", "#b5c6ef", "#d7b4eb"];
const art = (i: number) => `<svg viewBox="0 0 300 200" role="img" aria-label="Abstract landscape ${i + 1}"><rect width="300" height="200" fill="${palettes[i]}"/><circle cx="${75 + i * 35}" cy="65" r="42" fill="#fff8"/><path d="M0 170 Q80 ${i * 20} 160 140 T300 100 V200 H0Z" fill="#25372f"/><path d="M0 190 Q140 90 300 175 V200 H0Z" fill="#587764"/></svg>`;
const carouselStyles = [
  ["snap", "Snap rail", "A horizontal rail with native touch snapping.", ".track{display:flex;overflow:auto;scroll-snap-type:x mandatory}.slide{flex:0 0 85%;scroll-snap-align:center;margin-right:12px}"],
  ["fade", "Crossfade stories", "One story dissolves into the next.", ".slide{position:absolute;inset:0;opacity:0;transition:opacity .6s}.slide.active{opacity:1;z-index:1}"],
  ["coverflow", "Coverflow", "A centered card with angled neighbours.", ".track{perspective:700px}.slide{position:absolute;width:68%;left:16%;transform:translateX(calc(var(--offset)*72%)) rotateY(calc(var(--offset)*-32deg)) scale(.8);opacity:.5;transition:.5s}.slide.active{transform:none;opacity:1;z-index:2}"],
  ["stack", "Stacked postcards", "Cards lift from a layered deck.", ".slide{position:absolute;inset:8px 18px;transform:translateY(calc(var(--distance)*7px)) rotate(calc(var(--distance)*4deg));opacity:0;transition:.5s}.slide.active{opacity:1;z-index:3}.slide.next{opacity:.6;z-index:2}"],
  ["vertical", "Vertical chapters", "Move through an editorial sequence vertically.", ".slide{position:absolute;inset:0;transform:translateY(calc(var(--offset)*110%));transition:transform .5s}"],
  ["film", "Filmstrip", "A compact sequence of frames with a highlighted selection.", ".track{display:flex;overflow:auto;gap:10px;align-items:center}.slide{flex:0 0 65%;opacity:.45;transition:.3s}.slide.active{opacity:1}.slide:before{content:'▪ ▪ ▪ ▪ ▪ ▪ ▪';display:block;letter-spacing:10px;background:#080b09}"],
  ["split", "Split editorial", "Artwork and captions share a moving editorial panel.", ".slide{position:absolute;inset:0;display:grid;grid-template-columns:60% 40%;align-items:center;transform:translateX(calc(var(--offset)*110%));transition:.5s}.slide figcaption{font-size:19px}.slide svg{height:100%}"],
  ["zoom", "Zoom focus", "The next landscape comes into focus from a gentle zoom.", ".slide{position:absolute;inset:0;opacity:0;transform:scale(1.25);transition:transform .7s,opacity .7s}.slide.active{opacity:1;transform:scale(1);z-index:1}"],
  ["thumbnails", "Thumbnail navigator", "Jump directly to a slide with visual thumbnail controls.", ".slide{position:absolute;inset:0;opacity:0}.slide.active{opacity:1;z-index:1}.dots button{width:40px!important;height:24px!important;border-radius:3px!important}.dots svg{width:100%;height:100%}"],
] as const;
export const CAROUSELS = carouselStyles.map(([id, title, description, css]) => ({
  id: `carousel-${id}`, title, description, category: "Carousels", tag: "INTERACTIVE",
  html: `<section class="carousel" aria-label="${title}" tabindex="0"><div class="track">${palettes.map((_, i) => `<figure class="slide ${i === 0 ? "active" : ""}" style="--offset:${i};--distance:${i}">${art(i)}<figcaption>${["Quiet horizons", "Open spaces", "Into the blue", "A different perspective"][i]}</figcaption></figure>`).join("")}</div><div class="controls"><button class="prev" aria-label="Previous slide">←</button><div class="dots">${palettes.map((_, i) => `<button aria-label="Slide ${i + 1}" aria-pressed="${i === 0}">${id === "thumbnails" ? art(i) : ""}</button>`).join("")}</div><button class="next-button" aria-label="Next slide">→</button></div><span class="sr" aria-live="polite">Slide 1 of 4</span></section>`,
  css: `.carousel{width:min(90%,600px)}.track{height:clamp(120px,60vh,320px);position:relative;overflow:hidden;border-radius:12px}.slide{margin:0;background:#26372d;border-radius:10px;overflow:hidden}.slide svg{display:block;width:100%;height:calc(100% - 30px);object-fit:cover}.slide figcaption{padding:8px;font-size:12px}.controls{display:flex;align-items:center;justify-content:space-between;margin-top:12px;gap:12px}.controls button{background:#26372d;color:var(--accent);border:1px solid #687858;border-radius:8px;padding:6px 12px}.dots{display:flex;gap:8px}.dots button{padding:0;width:9px;height:9px;border-radius:50%;opacity:.4}.dots button[aria-pressed=true]{opacity:1;background:var(--accent)}.sr{position:absolute;width:1px;height:1px;overflow:hidden;clip-path:inset(50%)}${css}`,
  js: `const slides=[...document.querySelectorAll('.slide')],dots=[...document.querySelectorAll('.dots button')],track=document.querySelector('.track');let current=0;const native=${JSON.stringify(id === "snap" || id === "film")};function update(n,scroll=true){current=(n+4)%4;slides.forEach((s,i)=>{s.classList.toggle('active',i===current);s.classList.toggle('next',i===(current+1)%4);s.style.setProperty('--offset',i-current);s.style.setProperty('--distance',(i-current+4)%4);s.setAttribute('aria-hidden',String(!native&&i!==current))});dots.forEach((d,i)=>d.setAttribute('aria-pressed',String(i===current)));document.querySelector('.sr').textContent='Slide '+(current+1)+' of 4';if(native&&scroll)track.scrollTo({left:slides[current].offsetLeft,behavior:matchMedia('(prefers-reduced-motion:reduce)').matches?'instant':'smooth'})}document.querySelector('.prev').onclick=()=>update(current-1);document.querySelector('.next-button').onclick=()=>update(current+1);dots.forEach((d,i)=>d.onclick=()=>update(i));document.querySelector('.carousel').onkeydown=e=>{if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();update(current+(e.key==='ArrowRight'?1:-1))}};if(native)track.addEventListener('scroll',()=>{const nearest=slides.reduce((a,s,i)=>Math.abs(s.offsetLeft-track.scrollLeft)<Math.abs(slides[a].offsetLeft-track.scrollLeft)?i:a,0);update(nearest,false)},{passive:true});let start=0;track.onpointerdown=e=>start=e.clientX;track.onpointerup=e=>{if(!native&&Math.abs(e.clientX-start)>35)update(current+(e.clientX<start?1:-1))};update(0);`,
}));
export const EXTENDED_ELEMENTS = [
  ...CAROUSELS,
  ...ENGINE_ELEMENTS,
  ...CHART_ELEMENTS,
  { id: "gallery-lightbox", title: "Landscape lightbox", category: "Galleries & media", description: "An illustrated gallery with keyboard-accessible, enlarged artwork.", tag: "INTERACTIVE", html: `<div class="art-grid">${palettes.map((_, i) => `<button aria-label="Open landscape ${i + 1}">${art(i)}</button>`).join("")}</div><dialog><button class="close">Close ×</button><div class="large"></div></dialog>`, css: '.art-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px;width:85%}.art-grid button{padding:0;border:0;background:none;border-radius:10px;overflow:hidden}.art-grid svg{display:block;width:100%}dialog{background:#172019;border:1px solid var(--accent);color:white;width:min(90%,700px)}dialog::backdrop{background:#000b}.large svg{width:100%;max-height:70vh}.close{float:right;margin-bottom:12px}', js: "const dialog=document.querySelector('dialog');document.querySelectorAll('.art-grid button').forEach(b=>b.onclick=()=>{document.querySelector('.large').innerHTML=b.innerHTML;dialog.showModal()});document.querySelector('.close').onclick=()=>dialog.close();" },
  { id: "motion-spring", title: "Spring playground", category: "Hover effects", description: "A real Motion spring follows your click with a gentle bounce. Authored by Playground using Motion.dev.", tag: "Motion.dev", html: '<div class="spring-stage"><button class="spring-ball" aria-label="Move spring">✳</button><small>CLICK ANYWHERE TO MOVE</small></div>', css: '.spring-stage{position:relative;width:90%;height:80%;border:1px dashed #586b47;border-radius:18px}.spring-ball{position:absolute;left:20px;top:20px;width:62px;height:62px;background:var(--accent);border:0;border-radius:18px;color:#192013;font-size:36px}.spring-stage small{position:absolute;bottom:12px;width:100%;text-align:center}', js: '' },
  { id: "lenis-scroll", title: "Smooth chapter scroll", category: "Scroll effects", description: "Scroll through three illustrated chapters using the Lenis smooth-scroll engine. Native scrolling remains available with reduced motion.", tag: "Lenis", html: `<div class="smooth-scroll-window" tabindex="0" aria-label="Scrollable chapters"><div class="smooth-scroll-content">${palettes.slice(0,3).map((_,i)=>`<section><small>SCROLL ↓ · CHAPTER 0${i+1}</small>${art(i)}<h2>${["Take your time.","Find your rhythm.","Keep exploring."][i]}</h2></section>`).join('')}</div></div>`, css: '.smooth-scroll-window{width:100%;height:100%;overflow:auto;overscroll-behavior:contain}.smooth-scroll-content section{min-height:100vh;padding:28px;display:grid;place-content:center;text-align:center}.smooth-scroll-content svg{width:min(75vw,450px);max-height:50vh;margin-top:20px}.smooth-scroll-content section:nth-child(2){background:#283827}', js: '' },
  { id: "vanta-net", title: "Vanta constellation", category: "Backgrounds", description: "Vanta NET renders an interactive three-dimensional network using Three.js and WebGL. Authored scene by Playground.", tag: "Vanta", html: '<div id="vanta-scene"><div class="center"><small>VANTA · NET</small><h1>Connected<br>by possibility.</h1><p class="engine-status" aria-live="polite"></p></div></div>', css: '#vanta-scene{width:100%;height:100%;display:grid;place-items:center;background:radial-gradient(ellipse,#28432d,#111412)}#vanta-scene .center{z-index:1;pointer-events:none}.engine-status{font-size:12px}', js: '' },
];
